Repository thephpleague/commonmark, pull requests merged in 2020-04, with the labels that each got.

#423 Fix injectable event listener objects not having the environment or configuration injected
  CHANGELOG.md
  src/Environment.php
  tests/unit/EnvironmentTest.php
Labels: bug

#420 Implement new heading permalink extension
  .phpstorm.meta.php
  docs/1.4/extensions/heading-permalinks.md
  docs/1.4/extensions/overview.md
  docs/_data/menu.yml
  src/Extension/HeadingPermalink/HeadingPermalink.php
  src/Extension/HeadingPermalink/HeadingPermalinkExtension.php
  src/Extension/HeadingPermalink/HeadingPermalinkProcessor.php
  src/Extension/HeadingPermalink/HeadingPermalinkRenderer.php
  src/Extension/HeadingPermalink/Slug/DefaultSlugGenerator.php
  src/Extension/HeadingPermalink/Slug/SlugGeneratorInterface.php
  tests/functional/Extension/HeadingPermalink/HeadingPermalinkExtensionTest.php
  tests/unit/Extension/HeadingPermalink/Slug/DefaultSlugGeneratorTest.php
Labels: enhancement

#427 Pre-parsing events
  docs/1.4/customization/event-dispatcher.md
  src/DocParser.php
  src/Event/DocumentPreParsedEvent.php
  tests/unit/Event/DocumentPreParsedEventTest.php
Labels: enhancement

#222 Resolve parent class
  CHANGELOG.md
  docs/1.4/upgrading.md
  src/Environment.php
  tests/unit/Environment/FakeBlock1.php
  tests/unit/Environment/FakeBlock2.php
  tests/unit/Environment/FakeBlock3.php
  tests/unit/Environment/FakeInline1.php
  tests/unit/Environment/FakeInline2.php
  tests/unit/Environment/FakeInline3.php
  tests/unit/EnvironmentTest.php
Labels: enhancement, feedback wanted

#440 Fix injectables not being injected on some callable objects
  CHANGELOG.md
  src/Environment.php
  tests/unit/EnvironmentTest.php
  tests/unit/Event/FakeEventListener.php
  tests/unit/Event/FakeEventListenerInvokable.php
Labels: bug

#449 Allow event listeners to manipulate Markdown input prior to parsing
  CHANGELOG.md
  docs/1.4/customization/event-dispatcher.md
  src/DocParser.php
  src/Event/DocumentPreParsedEvent.php
  src/Input/MarkdownInput.php
  src/Input/MarkdownInputInterface.php
  tests/unit/Event/DocumentPreParsedEventTest.php
  tests/unit/Input/MarkdownInputTest.php
Labels: enhancement
