Repository thephpleague/commonmark, pull requests merged in 2020-10, with the labels that each got.

#556 Update the link for autoloading with composer
  docs/0.19/installation.md
  docs/1.0/installation.md
  docs/1.3/installation.md
  docs/1.4/installation.md
  docs/1.5/installation.md
  docs/2.0/installation.md
Labels: documentation, hacktoberfest

#558 Fix broken link to extensions from "Basic Usage"
  docs/1.3/basic-usage.md
  docs/1.4/basic-usage.md
  docs/1.5/basic-usage.md
  docs/2.0/basic-usage.md
Labels: documentation, hacktoberfest

#559 Update links to the Caret Version Range docs
  docs/0.19/installation.md
  docs/1.0/installation.md
  docs/1.3/installation.md
  docs/1.4/installation.md
  docs/1.5/installation.md
  docs/2.0/installation.md
Labels: documentation, hacktoberfest

#560 Refine inline parsing
  CHANGELOG.md
  docs/2.0/customization/inline-parsing.md
  docs/2.0/upgrading.md
  src/Delimiter/DelimiterParser.php
  src/Exception/InvalidOptionException.php
  src/Extension/Attributes/Parser/AttributesInlineParser.php
  src/Extension/Autolink/EmailAutolinkParser.php
  src/Extension/Autolink/UrlAutolinkParser.php
  src/Extension/CommonMark/Parser/Inline/AutolinkParser.php
  src/Extension/CommonMark/Parser/Inline/BacktickParser.php
  src/Extension/CommonMark/Parser/Inline/BangParser.php
  src/Extension/CommonMark/Parser/Inline/CloseBracketParser.php
  src/Extension/CommonMark/Parser/Inline/EntityParser.php
  src/Extension/CommonMark/Parser/Inline/EscapableParser.php
  src/Extension/CommonMark/Parser/Inline/HtmlInlineParser.php
  src/Extension/CommonMark/Parser/Inline/OpenBracketParser.php
  src/Extension/Footnote/Parser/AnonymousFootnoteRefParser.php
  src/Extension/Footnote/Parser/FootnoteRefParser.php
  src/Extension/Mention/Mention.php
  src/Extension/Mention/MentionExtension.php
  src/Extension/Mention/MentionParser.php
  src/Extension/SmartPunct/PunctuationParser.php
  src/Extension/SmartPunct/QuoteParser.php
  src/Extension/TaskList/TaskListItemMarkerParser.php
  src/Parser/Inline/InlineParserInterface.php
  src/Parser/Inline/InlineParserMatch.php
  src/Parser/Inline/NewlineParser.php
  src/Parser/InlineParserContext.php
  src/Parser/InlineParserEngine.php
  tests/functional/Extension/Mention/MentionExtensionTest.php
  tests/functional/Extension/Mention/MentionParserTest.php
  tests/unit/Environment/FakeInjectableInlineParser.php
  tests/unit/Extension/CommonMark/Parser/Inline/BacktickParserTest.php
  tests/unit/Extension/Mention/Generator/CallbackGeneratorTest.php
  tests/unit/Extension/Mention/MentionTest.php
  tests/unit/Parser/Inline/FakeInlineParser.php
  tests/unit/Parser/Inline/InlineParserMatchTest.php
Labels: enhancement, performance

#551 Rename "symbol" option to "prefix"
  CHANGELOG.md
  src/Extension/Mention/Mention.php
  src/Extension/Mention/MentionExtension.php
  src/Extension/Mention/MentionParser.php
  tests/functional/Extension/Mention/MentionExtensionTest.php
  tests/functional/Extension/Mention/MentionParserTest.php
  tests/unit/Extension/Mention/Generator/CallbackGeneratorTest.php
  tests/unit/Extension/Mention/MentionTest.php
Labels: enhancement

#550 Allow more than one character to be used as a symbol for MentionExtension
  CHANGELOG.md
  src/Extension/Mention/MentionParser.php
  tests/functional/Extension/Mention/MentionParserTest.php
Labels: enhancement

#561 Split PunctuationParser into two separate parsers
  CHANGELOG.md
  docs/2.0/upgrading.md
  src/Extension/SmartPunct/DashParser.php
  src/Extension/SmartPunct/EllipsesParser.php
  src/Extension/SmartPunct/PunctuationParser.php
  src/Extension/SmartPunct/SmartPunctExtension.php
Labels: enhancement

#565 Implement Node query functionality
  CHANGELOG.md
  docs/2.0/customization/abstract-syntax-tree.md
  src/Node/Query.php
  src/Node/Query/AndExpr.php
  src/Node/Query/ExpressionInterface.php
  src/Node/Query/OrExpr.php
  tests/unit/Node/QueryTest.php
Labels: enhancement

#566 Split the 2.0 upgrade guide into separate sections
  docs/2.0/upgrading.md
  docs/2.0/upgrading/consumers.md
  docs/2.0/upgrading/developers.md
  docs/2.0/upgrading/integrators.md
Labels: documentation

#574 Fix 2.0 mention docs to use pattern instead of regex
  docs/2.0/extensions/mentions.md
Labels: documentation

#577 Documentation changes
  docs/2.0/customization/delimiter-processing.md
  docs/2.0/extensions/attributes.md
  docs/2.0/upgrading/consumers.md
Labels: documentation, hacktoberfest

#583 Docs: Improve readabillity on large screens
  docs/custom.css
Labels: documentation, hacktoberfest

#582 Fix mentions when they appear after a non-word character such as \n or ,
  CHANGELOG.md
  src/Extension/Mention/MentionParser.php
  tests/functional/Extension/Mention/MentionParserTest.php
Labels: bug
